# Generated by Django 2.1.5 on 2021-02-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
